version: '2'
services:
    playground-kafka:
        build: ../kafka/workspace/
        container_name: playground-kafka
        expose:
            - "9092"
            - "2888"
            - "3888"
        volumes:
            - ../kafka/:/usr/src/playground
    playground-notificator:
        build: ../notificator/workspace/
        container_name: playground-notificator
        volumes:
            - ~/.aws:/home/playground/.aws
            - ../notificator:/usr/src/playground
        depends_on:
            - playground-kafka
        links:
            - "playground-kafka:kafka"
    playground-validator:
        build: ../url_validator/workspace/
        container_name: playground-validator
        volumes:
            - ../url_validator:/usr/src/playground
        depends_on:
            - playground-kafka
        links:
            - "playground-kafka:kafka"
    playground-webpage:
        build: ../webpage/workspace/
        container_name: playground-webpage
        ports:
            - "80:80"
        volumes:
            - ../webpage:/usr/src/playground
        depends_on:
            - playground-kafka
        links:
            - "playground-kafka:kafka"