version: '2'
services:
    playground-validator:
        stdin_open: true
        tty: true
        # just to have pid 1 blocked
        command: bash
        depends_on:
            - playground-kafka
            - playground-webpage